var obj = ReverseList()

var ll = ListNode(1)
ll.next = ListNode(2)
ll.next?.next = ListNode(3)
ll.next?.next?.next = ListNode(4)
ll.next?.next?.next?.next = ListNode(5)

print("LL:")
printLL(ll)
var rr = obj.reverseList(ll)
printLL(rr)

print("LL:")
printLL(ll)
var r = Reverse(ll)
printLL(r)

//var r1 = ReverseUsingRecursion(ll: ll)
//printLL(r1)

var l2 = ListNode(1)
l2.next = ListNode(2)
l2.next?.next = ListNode(3)
l2.next?.next?.next = ListNode(4)
l2.next?.next?.next?.next = ListNode(5)
print("Middle Element:")
print("LL:")
printLL(l2)
var middle = middleElement(ll: l2)
print("Middle : \(middle)")

var l3 = ListNode(1)
l3.next = ListNode(2)
l3.next?.next = ListNode(3)
l3.next?.next?.next = ListNode(3)
l3.next?.next?.next?.next = ListNode(4)
l3.next?.next?.next?.next?.next = ListNode(4)
l3.next?.next?.next?.next?.next?.next = ListNode(5)

print("Delete duplicates")
deleteDuplicates(l3)
